const armorList = [
    {
        armorId: 1,
        armorName: "Padded",
        armorAC: "11 + DEX",
        armorStrRequired: "",
        armorStealth: "Disadvantage",
        armorWeight: "8lbs",
        armorCost: "5gp",
    },
    {
        armorId: 2,
        armorName: "Leather",
        armorAC: "11 + DEX",
        armorStrRequired: "",
        armorStealth: "",
        armorWeight: "10lbs",
        armorCost: "10gp",
    },
    {
        armorId: 3,
        armorName: "Studded Leather",
        armorAC: "12 + DEX",
        armorStrRequired: "",
        armorStealth: "",
        armorWeight: "13lbs",
        armorCost: "45gp",
    },
    {
        armorId: 4,
        armorName: "Hide",
        armorAC: "12 + DEX (max 2)",
        armorStrRequired: "",
        armorStealth: "",
        armorWeight: "12lbs",
        armorCost: "10gp",
    },
    {
        armorId: 5,
        armorName: "Chain Shirt",
        armorAC: "13 + DEX (max 2)",
        armorStrRequired: "",
        armorStealth: "",
        armorWeight: "20lbs",
        armorCost: "50gp",
    },
    {
        armorId: 6,
        armorName: "Scale Mail",
        armorAC: "14 + DEX (max 2)",
        armorStrRequired: "",
        armorStealth: "Disadvantage",
        armorWeight: "45lbs",
        armorCost: "50gp",
    },
    {
        armorId: 7,
        armorName: "Breastplate",
        armorAC: "14 + DEX (max 2)",
        armorStrRequired: "",
        armorStealth: "",
        armorWeight: "20lbs",
        armorCost: "400gp",
    },
    {
        armorId: 8,
        armorName: "Half Plate",
        armorAC: "15 + DEX (max 2)",
        armorStrRequired: "",
        armorStealth: "Disadvantage",
        armorWeight: "40lbs",
        armorCost: "750gp",
    },
    {
        armorId: 9,
        armorName: "Ring Mail",
        armorAC: "14",
        armorStrRequired: "",
        armorStealth: "Disadvantage",
        armorWeight: "40lbs",
        armorCost: "30gp",
    },
    {
        armorId: 10,
        armorName: "Chain Mail",
        armorAC: "16",
        armorStrRequired: "STR 13",
        armorStealth: "Disadvantage",
        armorWeight: "55lbs",
        armorCost: "75gp",
    },
    {
        armorId: 11,
        armorName: "Splint",
        armorAC: "17",
        armorStrRequired: "STR 15",
        armorStealth: "Disadvantage",
        armorWeight: "60lbs",
        armorCost: "200gp",
    },
    {
        armorId: 12,
        armorName: "Plate",
        armorAC: "18",
        armorStrRequired: "STR 15",
        armorStealth: "Disadvantage",
        armorWeight: "65lbs",
        armorCost: "1500gp",
    },
    {
        armorId: 13,
        armorName: "Shield",
        armorAC: "+2 AC",
        armorStrRequired: "",
        armorStealth: "",
        armorWeight: "6lbs",
        armorCost: "10gp",
    },
]

export default armorList;