const potionList = [
    {
        potionId: 1,
        potionName: "Potion of Healing",
        potionDice: "2d4+2",
        potionUseTime: "Bonus Action",
        potionCost: "50gp",
        potionDescription: "When drunk, a creature regains 2d4 + 2 HP.",
        potionRarity: "Common",
    },
    {
        potionId: 2,
        potionName: "Greater Potion of Healing",
        potionDice: "4d4+4",
        potionUseTime: "Bonus Action",
        potionCost: "150gp",
        potionDescription: "When drunk, a creature regains 4d4 + 4 HP.",
        potionRarity: "Uncommon",
    },
    {
        potionId: 3,
        potionName: "Superior Potion of Healing",
        potionDice: "8d4+8",
        potionUseTime: "Bonus Action",
        potionCost: "450gp",
        potionDescription: "When drunk, a creature regains 8d4 + 8 HP.",
        potionRarity: "Rare",
    },
    {
        potionId: 4,
        potionName: "Supreme Potion of Healing",
        potionDice: "10d4+20",
        potionUseTime: "Bonus Action",
        potionCost: "1350gp",
        potionDescription: "When drunk, a creature regains 10d4 + 20 HP.",
        potionRarity: "Very Rare",
    },
    {
        potionId: 5,
        potionName: "Potion of Invisibility",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "300gp",
        potionDescription: "The creature becomes invisible for 1 hour or until it attacks or casts a spell.",
        potionRarity: "Very Rare",
    },
    {
        potionId: 6,
        potionName: "Potion of Speed",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "400gp",
        potionDescription: "Grants the effect of the Haste spell for 1 minute.",
        potionRarity: "Very Rare",
    },
    {
        potionId: 7,
        potionName: "Potion of Fire Breath",
        potionDice: "4d6",
        potionUseTime: "Bonus Action",
        potionCost: "150gp",
        potionDescription: "Allows the drinker to exhale fire in a 30 ft line (3 times within 1 hour).",
        potionRarity: "Uncommon",
    },
    {
        potionId: 8,
        potionName: "Potion of Flying",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "500gp",
        potionDescription: "Gives a flying speed of 60 feet for 1 hour.",
        potionRarity: "Very Rare",
    },
    {
        potionId: 9,
        potionName: "Potion of Water Breathing",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "200gp",
        potionDescription: "Allows the drinker to breathe underwater for 1 hour.",
        potionRarity: "Uncommon",
    },
    {
        potionId: 10,
        potionName: "Potion of Heroism",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "250gp",
        potionDescription: "Grants 10 temporary HP and the effects of the Bless spell for 1 hour.",
        potionRarity: "Rare",
    },
    {
        potionId: 11,
        potionName: "Potion of Mind Reading",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "300gp",
        potionDescription: "Allows you to cast Detect Thoughts (save DC 13) for 1 minute.",
        potionRarity: "Rare",
    },
    {
        potionId: 12,
        potionName: "Potion of Gaseous Form",
        potionDice: "",
        potionUseTime: "Action",
        potionCost: "300gp",
        potionDescription: "Transforms the drinker into a cloud of mist for up to 1 hour.",
        potionRarity: "Rare",
    },
]

export default potionList;