const weaponList = [
    {
        weaponId: 1,
        weaponName: "Club",
        weaponDmgDice: "1d4",
        weaponType: "Melee",
        weaponAttribute: "Light",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 2,
        weaponName: "Dagger",
        weaponDmgDice: "1d4",
        weaponType: "Melee",
        weaponAttribute: "Finesse, Light, Thrown",
        weaponRange: "20/60ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 3,
        weaponName: "Greatclub",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Two-Handed",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 4,
        weaponName: "Handaxe",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Light, Thrown",
        weaponRange: "20/60ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 5,
        weaponName: "Javelin",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Thrown",
        weaponRange: "30/120ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 6,
        weaponName: "Light Hammer",
        weaponDmgDice: "1d4",
        weaponType: "Melee",
        weaponAttribute: "Light, Thrown",
        weaponRange: "20/60ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 7,
        weaponName: "Mace",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Bludgeoning",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 8,
        weaponName: "Quarterstaff",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Versatile (1d8)",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 9,
        weaponName: "Sickle",
        weaponDmgDice: "1d4",
        weaponType: "Melee",
        weaponAttribute: "Light",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 10,
        weaponName: "Spear",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Thrown, Versatile (1d8)",
        weaponRange: "20/60ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 11,
        weaponName: "Light Crossbow",
        weaponDmgDice: "1d8",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition, Loading, Two-Handed",
        weaponRange: "80/320ft",
        weaponAmmoType: "Bolts",
    },
    {
        weaponId: 12,
        weaponName: "Dart",
        weaponDmgDice: "1d4",
        weaponType: "Ranged",
        weaponAttribute: "Finesse, Thrown",
        weaponRange: "20/60ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 13,
        weaponName: "Shortbow",
        weaponDmgDice: "1d6",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition, Two-Handed",
        weaponRange: "80/320ft",
        weaponAmmoType: "Arrows",
    },
    {
        weaponId: 14,
        weaponName: "Sling",
        weaponDmgDice: "1d4",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition",
        weaponRange: "30/120ft",
        weaponAmmoType: "Stones",
    },
    {
        weaponId: 15,
        weaponName: "Battleaxe",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Versatile (1d10)",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 16,
        weaponName: "Flail",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Bludgeoning",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 17,
        weaponName: "Glaive",
        weaponDmgDice: "1d10",
        weaponType: "Melee",
        weaponAttribute: "Heavy, Reach, Two-Handed",
        weaponRange: "10ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 18,
        weaponName: "Greataxe",
        weaponDmgDice: "1d12",
        weaponType: "Melee",
        weaponAttribute: "Heavy, Two-Handed",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 19,
        weaponName: "Greatsword",
        weaponDmgDice: "2d6",
        weaponType: "Melee",
        weaponAttribute: "Heavy, Two-Handed",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 20,
        weaponName: "Halberd",
        weaponDmgDice: "1d10",
        weaponType: "Melee",
        weaponAttribute: "Heavy, Reach, Two-Handed",
        weaponRange: "10ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 21,
        weaponName: "Lance",
        weaponDmgDice: "1d12",
        weaponType: "Melee",
        weaponAttribute: "Reach, Special",
        weaponRange: "10ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 22,
        weaponName: "Longsword",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Versatile (1d10)",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 23,
        weaponName: "Maul",
        weaponDmgDice: "2d6",
        weaponType: "Melee",
        weaponAttribute: "Heavy, Two-Handed",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 24,
        weaponName: "Morningstar",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Piercing",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 25,
        weaponName: "Pike",
        weaponDmgDice: "1d10",
        weaponType: "Melee",
        weaponAttribute: "Heavy, Reach, Two-Handed",
        weaponRange: "10ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 26,
        weaponName: "Rapier",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Finesse",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 27,
        weaponName: "Scimitar",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Finesse, Light",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 28,
        weaponName: "Shortsword",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Finesse, Light",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 29,
        weaponName: "Trident",
        weaponDmgDice: "1d6",
        weaponType: "Melee",
        weaponAttribute: "Thrown, Versatile (1d8)",
        weaponRange: "20/60ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 30,
        weaponName: "War Pick",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Piercing",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 31,
        weaponName: "Warhammer",
        weaponDmgDice: "1d8",
        weaponType: "Melee",
        weaponAttribute: "Versatile (1d10)",
        weaponRange: "5ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 32,
        weaponName: "Whip",
        weaponDmgDice: "1d4",
        weaponType: "Melee",
        weaponAttribute: "Finesse, Reach",
        weaponRange: "10ft",
        weaponAmmoType: "none",
    },
    {
        weaponId: 33,
        weaponName: "Blowgun",
        weaponDmgDice: "1",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition, Loading",
        weaponRange: "25/100ft",
        weaponAmmoType: "Needles",
    },
    {
        weaponId: 34,
        weaponName: "Hand Crossbow",
        weaponDmgDice: "1d6",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition, Light, Loading",
        weaponRange: "30/120ft",
        weaponAmmoType: "Bolts",
    },
    {
        weaponId: 35,
        weaponName: "Heavy Crossbow",
        weaponDmgDice: "1d10",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition, Heavy, Loading, Two-Handed",
        weaponRange: "100/400ft",
        weaponAmmoType: "Bolts",
    },
    {
        weaponId: 36,
        weaponName: "Longbow",
        weaponDmgDice: "1d8",
        weaponType: "Ranged",
        weaponAttribute: "Ammunition, Heavy, Two-Handed",
        weaponRange: "150/600ft",
        weaponAmmoType: "Arrows",
    },
    {
        weaponId: 37,
        weaponName: "Net",
        weaponDmgDice: "—",
        weaponType: "Ranged",
        weaponAttribute: "Special, Thrown",
        weaponRange: "5/15ft",
        weaponAmmoType: "none",
    },
]
export default weaponList;